newsApi:
  baseUrl: "https://newsapi.org"
  apiKey: "0b5c38466d0a450bbb714c52faa8f5bc"
  path:
    everything: "/v2/everything"
    topHeadlines: "/v2/top-headlines"
    sources: "/v2/top-headlines/sources"

spring:
  security:
    oauth2:
      client:
        registration:
          api-client-oidc:
            provider: spring
            client-id: api-client
            client-secret: secret
            authorization-grant-type: authorization_code
            scope: openid
            client-name: api-client-oidc
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
          api-client-authorization-code:
            provider: spring
            client-id: api-client
            client-secret: secret
            authorization-grant-type: authorization_code
            scope: api.read, api.write
            client-name: api-client-authorization-code
            redirect-uri: "http://127.0.0.1:8080/authorized"
        provider:
          spring:
            issuer-uri: http://auth-server:9000

