server:
  port: 9000

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

config:
  provider:
    settings:
      issuer: http://auth-server:9000

  client:
    reactFrontend:
      id: snoop_87037db79d7c1abb5803321d75d56a84
      secret: vE8SjPX1KI
      uri: http://127.0.0.1:3000
      redirectUri: ${config.client.reactFrontend.uri}/authorized
  cors:
    allowedOrigins:
      - ${config.client.reactFrontend.uri}
      - "*"
    allowedHeaders:
      - "*"
    allowedMethods:
      - "*"

