server:
  port: 9000
logging:
  level:
    root: TRACE
    org.springframework.web: TRACE
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

config:
  provider:
    settings:
      issuer: "http://auth-server:9000"

  #  client:
  #    reactFrontend:
  #      id: snoop_87037db79d7c1abb5803321d75d56a84
  #      secret: vE8SjPX1KI
  #      uri: http://127.0.0.1:3000
  #      redirectUri: ${config.client.reactFrontend.uri}/authorized

  client:
    gateway:
      id: gateway-client
      secret: secret
      uri: "http://127.0.0.1:8070"
      redirectCodeUri: "${config.client.gateway.uri}/login/oauth2/code/gateway-client-oidc"
      redirectAuthorizedUri: "${config.client.gateway.uri}/authorized"

  cors:
    allowedOrigins:
      #      - ${config.client.reactFrontend.uri}
      - ${config.client.gateway.uri}
      - "*"
    allowedHeaders:
      - "*"
    allowedMethods:
      - "*"